"use strict";var C=Object.defineProperty;var n=(e,t)=>C(e,"name",{value:t,configurable:!0});var s=Symbol.for("__cloudflare-context__");function p(e={async:!1}){return e.async?y():x()}n(p,"getCloudflareContext");function i(){return globalThis[s]}n(i,"getCloudflareContextFromGlobalScope");function c(){return globalThis.__NEXT_DATA__?.nextExport===!0}n(c,"inSSG");function x(){const e=i();if(e)return e;throw c()?new Error("\n\nERROR: `getCloudflareContext` has been called in sync mode in either a static route or at the top level of a non-static one, both cases are not allowed but can be solved by either:\n  - make sure that the call is not at the top level and that the route is not static\n  - call `getCloudflareContext({async: true})` to use the `async` mode\n  - avoid calling `getCloudflareContext` in the route\n"):new Error(f)}n(x,"getCloudflareContextSync");async function y(){const e=i();if(e)return e;if(process.env.NEXT_RUNTIME==="nodejs"||c()){const o=await b();return m(o),o}throw new Error(f)}n(y,"getCloudflareContextAsync");function m(e){const t=globalThis;t[s]=e}n(m,"addCloudflareContextToNodejsGlobal");async function b(e){const{getPlatformProxy:t}=await import(`${"__wrangler".replaceAll("_","")}`),o=e?.environment??process.env.NEXT_DEV_WRANGLER_ENV,{env:r,cf:l,ctx:a}=await t({...e,envFiles:[],environment:o});return{env:r,cf:l,ctx:a}}n(b,"getCloudflareContextFromWrangler");var f=`

ERROR: \`getCloudflareContext\` has been called without having called \`initOpenNextCloudflareForDev\` from the Next.js config file.
You should update your Next.js config file as shown below:

   \`\`\`
   // next.config.mjs

   import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";

   initOpenNextCloudflareForDev();

   const nextConfig = { ... };
   export default nextConfig;
   \`\`\`

`,_={name:"cloudflare-asset-resolver",async maybeGetAssetResult(e){const{ASSETS:t}=p().env;if(!t||!w(globalThis.__ASSETS_RUN_WORKER_FIRST__,e.rawPath))return;const{method:o,headers:r}=e;if(o!=="GET"&&o!="HEAD")return;const l=new URL(e.rawPath,"https://assets.local"),a=await t.fetch(l,{headers:r,method:o});if(a.status===404){await a.body?.cancel();return}return{type:"core",statusCode:a.status,headers:Object.fromEntries(a.headers.entries()),body:E(o,a),isBase64Encoded:!1}}};function E(e,t){return e==="HEAD"?null:t.body||new ReadableStream}n(E,"getResponseBody");function w(e,t){if(!Array.isArray(e))return e??!1;let o=!1;for(let r of e){let l=!0;if(r.startsWith("!"))r=r.slice(1),l=!1;else if(o)continue;if(new RegExp(`^${r.replace(/([[\]().*+?^$|{}\\])/g,"\\$1").replace("\\*",".*")}$`).test(t))if(l)o=!0;else return!1}return o}n(w,"isUserWorkerFirst");var R=_;function v(e={}){const{incrementalCache:t,tagCache:o,queue:r,cachePurge:l,enableCacheInterception:a=!1,routePreloadingBehavior:h="none"}=e;return{default:{override:{wrapper:"cloudflare-node",converter:"edge",proxyExternalRequest:"fetch",incrementalCache:u(t),tagCache:d(o),queue:g(r),cdnInvalidation:N(l)},routePreloadingBehavior:h},edgeExternals:["node:crypto"],cloudflare:{useWorkerdCondition:!0},dangerous:{enableCacheInterception:a},middleware:{external:!0,override:{wrapper:"cloudflare-edge",converter:"edge",proxyExternalRequest:"fetch",incrementalCache:u(t),tagCache:d(o),queue:g(r)},assetResolver:n(()=>R,"assetResolver")}}}n(v,"defineCloudflareConfig");function u(e="dummy"){return typeof e=="string"||typeof e=="function"?e:()=>e}n(u,"resolveIncrementalCache");function d(e="dummy"){return typeof e=="string"||typeof e=="function"?e:()=>e}n(d,"resolveTagCache");function g(e="dummy"){return typeof e=="string"||typeof e=="function"?e:()=>e}n(g,"resolveQueue");function N(e="dummy"){return typeof e=="string"||typeof e=="function"?e:()=>e}n(N,"resolveCdnInvalidation");var T=v({dangerous:{buildConfig:{external:["pg-cloudflare","expo-sqlite","fs","path","os","pg"],minify:!1}}});export{T as default};
